apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator-deployment
  labels:
    app: loadgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      containers:
      - name: loadgenerator
        image: lakulos/loadgenerator:latest
        env:
          - name: FRONTEND_ADDR
            value: "frontend:80"
          - name: USERS
            value: "10"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"


---

apiVersion: v1
kind: Service
metadata:
  name: loadgenerator
  labels:
    app: loadgenerator
spec:
  type: ClusterIP
  selector:
    app: loadgenerator
  ports:
    - port: 80


