apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice-deployment
  labels:
    app: shippingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
      - name: shippingservice
        image: lakulos/shippingservice:latest
        env:
          - name: PORT
            value: "50051"
          - name: DISABLE_PROFILER
            value: "1"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"


---

apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  labels:
    app: shippingservice
spec:
  type: ClusterIP
  selector:
    app: shippingservice
  ports:
    - port: 50051
      targetPort: 50051


